-- tests/test_ui.lua — builds the panel and the settings category against
-- stub widgets. This can't check layout, but it catches calls to missing
-- helpers, typos and wiring mistakes between the UI and Config.

local T = ...
local test, eq, truthy = T.test, T.eq, T.truthy
local mock = T.mock

test("registers the settings category and builds the panel", function()
  local ns = T.load()
  truthy(mock.categories.EditModeGuideLines, "settings category")
  truthy(ns.UI.panel, "edit mode panel")
  truthy(ns.UI.settings, "settings frame")
  truthy(not ns.UI.panel.shown)
end)

test("the panel opens next to the Edit Mode window and closes with it", function()
  local ns = T.load()
  mock.enterEditMode()
  truthy(ns.UI.panel.shown)
  local p = ns.UI.panel.points[1]
  eq({ p[1], p[2], p[3] }, { "TOPLEFT", mock.manager, "TOPRIGHT" })
  mock.exitEditMode()
  truthy(not ns.UI.panel.shown)
  ns.Config.SetSetting("showPanel", false)
  mock.enterEditMode()
  truthy(not ns.UI.panel.shown, "stays closed when the setting is off")
  truthy(ns.UI.ShowPanel(), "but can still be opened")
  truthy(ns.UI.panel.shown)
end)

test("all editors refresh without errors, empty and with guides", function()
  local ns = T.load()
  ns.UI.panel:Show()
  ns.UI.settings:Show()
  ns.UI.Refresh()
  ns.Config.Add("v", 50)
  ns.Config.Add("h", 33.3, "red")
  ns.Config.SetEnabled(2, false)
  ns.UI.Refresh()
  local ed = ns.UI.panel.editor
  eq(#ed.rows, 2)
  eq(ed.rows[1].orient.text, "Vertical")
  eq(ed.rows[2].orient.text, "Horizontal")
  eq(ed.rows[2].percent.text, "33.3")
  eq(ed.rows[2].enabled.checked, false)
  eq(ed.rows[2].swatch.fill.color.r, 1)
  ns.Config.Remove(1)
  eq(ed.rows[2].shown, false, "spare rows are hidden")
  eq(ed.rows[1].percent.text, "33.3")
end)

test("adding a guide from the panel goes through Config and reports errors", function()
  local ns = T.load()
  mock.enterEditMode()
  local ed = ns.UI.panel.editor
  ed.orientButton:Click()
  eq(ed.orientButton.text, "Horizontal")
  ed.percentInput:SetText("40")
  ed.addButton:Click()
  eq(ns.Config.Count(), 1)
  eq(ns.Config.Get(1).orientation, "horizontal")
  eq(ns.Config.Get(1).percent, 40)
  eq(ns.Config.Get(1).color, ns.Guides.ParseColor("green"))
  eq(ed.percentInput.text, "", "cleared after adding")
  eq(ed.errorLabel.text, "")
  ed.percentInput:SetText("40")
  ed.percentInput:Enter()
  eq(ns.Config.Count(), 1, "duplicate refused")
  truthy(ed.errorLabel.text:match("already"), ed.errorLabel.text)
  ed.percentInput:SetText("x")
  ed.addButton:Click()
  truthy(ed.errorLabel.text:match("percentage"))
end)

test("the new-guide swatch picks the color for the next guide", function()
  local ns = T.load()
  mock.enterEditMode()
  local ed = ns.UI.panel.editor
  ed.newSwatch:Click()
  truthy(mock.colorPicker, "color picker opened")
  eq(mock.colorPicker.r, 0.25)
  eq(mock.colorPicker.hasOpacity, true)
  mock.pickColor(1, 0, 0)
  eq(ed.new.color, { r = 1, g = 0, b = 0, a = 1 })
  ed.percentInput:SetText("50")
  ed.addButton:Click()
  eq(ns.Config.Get(1).color, { r = 1, g = 0, b = 0, a = 1 })
end)

test("row controls edit the guide: percent, orientation, color, shown, delete", function()
  local ns = T.load()
  mock.enterEditMode()
  ns.Config.Add("v", 50)
  ns.Config.Add("v", 20)
  local ed = ns.UI.panel.editor
  local row = ed.rows[1]
  row.percent:SetText("60")
  row.percent:Enter()
  eq(ns.Config.Get(1).percent, 60)
  eq(row.percent.text, "60")
  row.percent:SetText("20")
  row.percent:Enter()
  eq(ns.Config.Get(1).percent, 60, "duplicate refused")
  eq(row.percent.text, "60", "the box shows the real value again")
  truthy(ed.errorLabel.text:match("already"))
  row.orient:Click()
  eq(ns.Config.Get(1).orientation, "horizontal")
  eq(row.orient.text, "Horizontal")
  row.swatch:Click()
  eq(mock.colorPicker.g, 1, "opened on the guide's color")
  mock.pickColor(0, 0, 1, 0.5)
  eq(ns.Config.Get(1).color, { r = 0, g = 0, b = 1, a = 0.5 })
  mock.cancelColor()
  eq(ns.Config.Get(1).color, ns.Guides.ParseColor("green"), "cancel restores the original")
  row.enabled:SetChecked(false)
  row.enabled:Click()
  eq(ns.Config.Get(1).enabled, false)
  row.delete:Click()
  eq(ns.Config.Count(), 1)
  eq(ns.Config.Get(1).percent, 20)
  eq(ed.rows[1].percent.text, "20", "row 1 now shows the remaining guide")
end)

test("setting checkboxes and the thickness box go through Config", function()
  local ns = T.load()
  ns.UI.settings:Show()
  local ed = ns.UI.settings.editor
  ed.checks.showOutsideEditMode:SetChecked(true)
  ed.checks.showOutsideEditMode:Click()
  eq(ns.db.showOutsideEditMode, true)
  ed.checks.aboveFrames:SetChecked(true)
  ed.checks.aboveFrames:Click()
  eq(ns.db.aboveFrames, true)
  ed.checks.enabled:SetChecked(false)
  ed.checks.enabled:Click()
  eq(ns.db.enabled, false)
  ed.thicknessInput:SetText("4")
  ed.thicknessInput:Enter()
  eq(ns.db.thickness, 4)
  ed.thicknessInput:SetText("40")
  ed.thicknessInput:Enter()
  eq(ns.db.thickness, 4)
  eq(ed.thicknessInput.text, "4", "reset to the real value")
  truthy(ed.errorLabel.text:match("thickness"))
  ns.UI.settings.showPanelCheck:SetChecked(false)
  ns.UI.settings.showPanelCheck:Click()
  eq(ns.db.showPanel, false)
end)

test("Open and OpenEditMode", function()
  local ns = T.load()
  truthy(ns.UI.Open())
  eq(mock.opened, "EditModeGuideLines", "settings when Edit Mode is closed")
  truthy(ns.UI.OpenEditMode())
  truthy(mock.manager.shown)
  truthy(ns.UI.panel.shown)
  ns.UI.HidePanel()
  truthy(ns.UI.Open())
  truthy(ns.UI.panel.shown, "the panel when Edit Mode is open")
  mock.exitEditMode()
  mock.inCombat = true
  truthy(not ns.UI.OpenEditMode())
  truthy(T.lastPrinted():match("combat"))
  mock.inCombat = false
  mock.cannotEnterEditMode = true
  truthy(not ns.UI.OpenEditMode())
  ns.UI.settings.openButton:Click()
  truthy(not mock.manager.shown)
end)

test("without Edit Mode on the client /emg opens the settings and the panel is only opened on demand", function()
  local ns = T.load(nil, { noEditMode = true })
  truthy(ns.UI.panel and not ns.UI.panel.shown)
  truthy(ns.UI.settings)
  truthy(ns.UI.ShowPanel(), "/emg panel still works")
  eq(ns.UI.panel.points[1][1], "CENTER", "centered: nothing to dock to")
  ns.UI.HidePanel()
  truthy(ns.UI.Open())
  eq(mock.opened, "EditModeGuideLines")
  truthy(not ns.UI.OpenEditMode())
  ns.UI.settings:Show()
  ns.UI.Refresh()
end)
