-- tests/test_commands.lua — /emg.

local T = ...
local test, eq, truthy = T.test, T.eq, T.truthy
local mock = T.mock

local function run(ns, msg)
  ns.Commands.Run(msg)
  return T.lastPrinted()
end

test("registers /emg and /guidelines", function()
  T.load()
  eq(_G.SLASH_EDITMODEGUIDELINES1, "/emg")
  eq(_G.SLASH_EDITMODEGUIDELINES2, "/guidelines")
  truthy(_G.SlashCmdList.EDITMODEGUIDELINES)
end)

test("add, list, del and clear", function()
  local ns = T.load()
  eq(run(ns, "add v 50 green"), "GuideLines: added 1. Vertical 50% (lines at 25% and 75%)")
  eq(ns.Config.Get(1).color, ns.Guides.ParseColor("green"))
  eq(run(ns, "add H 33.3"), "GuideLines: added 2. Horizontal 33.3% (lines at 33.35% and 66.65%)")
  truthy(run(ns, "add v 50"):match("already"))
  truthy(run(ns, "add x 50"):match("orientation"))
  truthy(run(ns, "add v"):match("percentage"))
  truthy(run(ns, "add v 5 nope"):match("color"))
  eq(ns.Config.Count(), 2)
  run(ns, "list")
  eq(#mock.printed, 8)
  truthy(mock.printed[7]:match("^|cff33ccffGuideLines|r: 1%. |cff40ff40Vertical"), mock.printed[7])
  eq(run(ns, "del 1"), "GuideLines: removed 1. Vertical 50% (lines at 25% and 75%)")
  eq(ns.Config.Count(), 1)
  truthy(run(ns, "del 5"):match("must be 1 to 1"))
  truthy(run(ns, "del"):match("must be 1 to 1"))
  eq(run(ns, "clear"), "GuideLines: removed 1 guide")
  eq(run(ns, "clear"), "GuideLines: there were no guides")
  truthy(run(ns, "del 1"):match("no guides"))
  truthy(run(ns, "list"):match("no guides"))
end)

test("percent, flip, color and toggle edit a guide", function()
  local ns = T.load()
  run(ns, "add v 50")
  eq(run(ns, "percent 1 60"), "GuideLines: now 1. Vertical 60% (lines at 20% and 80%)")
  truthy(run(ns, "percent 1 abc"):match("percentage"))
  eq(run(ns, "set 1 0"), "GuideLines: now 1. Vertical 0% (one line at 50%)")
  eq(run(ns, "flip 1"), "GuideLines: now 1. Horizontal 0% (one line at 50%)")
  eq(run(ns, "color 1 #ff0000"), "GuideLines: now 1. Horizontal 0% (one line at 50%)")
  eq(ns.Config.Get(1).color, { r = 1, g = 0, b = 0, a = 1 })
  truthy(run(ns, "colour 1 nope"):match("color"))
  eq(run(ns, "toggle 1"), "GuideLines: now 1. Horizontal 0% (one line at 50%) (off)")
  eq(ns.Config.Get(1).enabled, false)
  truthy(run(ns, "toggle 2"):match("must be 1 to 1"))
end)

test("on/off, show/hide, above, thickness", function()
  local ns = T.load()
  eq(run(ns, "off"), "GuideLines: guides off")
  eq(ns.db.enabled, false)
  eq(run(ns, "on"), "GuideLines: guides on")
  eq(run(ns, "show"), "GuideLines: guides outside Edit Mode on")
  eq(ns.db.showOutsideEditMode, true)
  eq(run(ns, "hide"), "GuideLines: guides outside Edit Mode off")
  eq(run(ns, "above"), "GuideLines: drawing above frames on")
  eq(ns.db.aboveFrames, true)
  eq(run(ns, "above"), "GuideLines: drawing above frames off")
  eq(run(ns, "thickness 2"), "GuideLines: thickness 2 px")
  eq(ns.db.thickness, 2)
  truthy(run(ns, "thickness 99"):match("thickness must be"))
  eq(ns.db.thickness, 2)
end)

test("no argument opens the panel or settings; panel, editmode, help and unknown", function()
  local ns = T.load()
  run(ns, "")
  eq(mock.opened, "EditModeGuideLines")
  run(ns, "editmode")
  truthy(mock.manager.shown)
  ns.UI.HidePanel()
  run(ns, "panel")
  truthy(ns.UI.panel.shown)
  ns.UI.HidePanel()
  run(ns, "  ")
  truthy(ns.UI.panel.shown)
  local before = #mock.printed
  run(ns, "help")
  truthy(#mock.printed > before + 4)
  truthy(run(ns, "bogus"):match("unknown command"))
end)
